services:
  nextjs:
    container_name: nextjs-kanami-dev
    build:
      context: ./kanamigame-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./kanamigame-app:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://kanami:kanamipassword@postgresql:5432/kanami_dev_db?schema=public
    # command: pnpm run dev
    depends_on:
      - postgresql
    networks:
      - kanami-dev-network

  postgresql:
    container_name: postgresql-kanami-dev
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kanami
      - POSTGRES_PASSWORD=kanamipassword
      - POSTGRES_DB=kanami_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kanami-dev-network

networks:
  kanami-dev-network:
      driver: bridge

volumes:
  postgres_data:
    name: kanami-dev-postgres-data
    driver: local