FROM node:18-bullseye-slim

# Installer les paquets nécessaires pour les dépendances natives
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

RUN apt update && apt install -y curl

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port utilisé par Next.js
EXPOSE 3000

# Définir la commande par défaut
CMD ["npm", "run", "dev"]